### ISSUE TITLE
car play emulator crashes/ not working

### ISSUE THREAD

**Issue by Niall-Kenny** [oguzhnatly/flutter_carplay#7] opened 2021-11-30 15:43 UTC
Hi there,

I use an **m1 macbook** air and followed the instructions outlined on pub.dev and [in this issue for setting up entitlements](https://github.com/oguzhnatly/flutter_carplay/issues/3), your response was very useful! 🙂

[This is the project](https://github.com/Niall-Kenny/car_play_test) I used when encountering the following errors:

1. iphone app crashes when I open the carplay simulator
2. carplay simulator displays grey screen when connected

####  1. iphone app crashes when I open the carplay simulator

https://user-images.githubusercontent.com/45692434/144070060-d2ecebb0-7626-4ecf-af8b-5814c69d658b.mov

repro steps:

1. make sure carplay simulator is closed
2. run flutter app
3. open carplay simulator 
4. iphone app crashes

####  2. carplay simulator displays grey screen when connected

https://user-images.githubusercontent.com/45692434/144070610-ef750fdd-25d8-4bef-8fea-0c646582c7ab.mov

repro steps:

1. make sure carplay simulator is open
2. run flutter app
4. open carplay app
5. carplay app has grey screen

**To note:**
RunnerDebug.entitlements is used in this project, I did also try Runner.entitlements but with no effect.

**Comment by oguzhnatly** [comment] 2021-12-07 19:29
Hello, @Niall-Kenny. Thank you for reporting your concern about the bug! 

While in debugging mode in Flutter or when a flutter hot reload is fired, it may not properly reload or set the current template from flutter cli to apple carplay and may show you a gray screen because no template has been set. Could you please re-run flutter start and see if the gray screen is still present in your current project when the simulator is connected to carplay simulator? If you want to use hot reload, try updating the root template. It is important to note that you must always use Runner.entitlements. 

I hope it is helpful to you; please let me know if any other errors occur in your case.

**Comment by mastro993** [comment] 2022-03-04 08:20
Same problem for me.
I followed the instructions and implemented the library in my app. 
The app starts correctly but it crashes whenever I open the app on the CarPlay emulator. 
Running with XCode I found that the cause of the problem is in the AppDelegate.swift that throws the following error:

> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Unsupported object <CPTabBarTemplate: 0x6000004379f0> <identifier: B43041AD-9862-451C-BF67-FF0D57C5B8FE, userInfo: (null), tabTitle: (null), tabImage: (null), showsTabBadge: 0> passed to setRootTemplate:animated:completion:. Allowed classes: (null)'
terminating with uncaught exception of type NSException
CoreSimulator 783.5 - Device: iPhone 13 Pro Max (EDBB6254-C444-40C2-BD49-4D4646251821) - Runtime: iOS 15.2 (19C51) - DeviceType: iPhone 13 Pro Max
_LSContextInitReturningError() failed with error Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)" UserInfo={_LSFunction=_LSSchemaConfigureForStore, ExpectedSimulatorHash={length = 32, bytes = 0xf6701f12 bb1a56bb bba5f39f 3f7801a6 ... f9fe6ee0 ef307d24 }, _LSLine=405, WrongSimulatorHash={length = 32, bytes = 0x9da4b2b1 56f7ac19 1a99bc21 b7ec95c2 ... c4004d14 03ef83dc }}

**Comment by EArminjon** [comment] 2022-03-05 13:20
```
2022-03-05 14:18:54.123193+0100 Runner[62302:4633665] flutter: On carPlay connection change : connected
2022-03-05 14:18:54.145042+0100 Runner[62302:4633382] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Unsupported object <CPTabBarTemplate: 0x600002eb1b90> <identifier: 9BF1FB47-1108-4B07-A99D-FB70C58C836C, userInfo: (null), tabTitle: (null), tabImage: (null), showsTabBadge: 0> passed to setRootTemplate:animated:completion:. Allowed classes: (null)'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010ea52ba4 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x000000010c536be7 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010ea52a82 -[NSException initWithCoder:] + 0
	3   CarPlay                             0x000000013bf9a786 CPAssertAllowedClasses + 147
	4   CarPlay                             0x000000013bf9a64b -[CPInterfaceController setRootTemplate:animated:completion:] + 288
	5   flutter_carplay                     0x000000010c3be4a5 $s15flutter_carplay27FlutterCarPlaySceneDelegateC019templateApplicationF0_10didConnectySo010CPTemplateiF0C_So21CPInterfaceControllerCtF + 725
	6   flutter_carplay                     0x000000010c3be5f7 $s15flutter_carplay27FlutterCarPlaySceneDelegateC019templateApplicationF0_10didConnectySo010CPTemplateiF0C_So21CPInterfaceControllerCtFTo + 71
	7   CarPlay                             0x000000013bfcc456 -[CPTemplateApplicationScene _deliverInterfaceControllerToDelegate] + 620
	8   CarPlay                             0x000000013bfcb1d1 __64-[CPTemplateApplicationScene initWithSession:connectionOptions:]_block_invoke.23 + 125
	9   Foundation                          0x000000010bea0178 -[__NSObserver _doit:] + 287
	10  CoreFoundation                      0x000000010e992f2c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	11  CoreFoundation                      0x000000010e992ef2 ___CFXRegistrationPost_block_invoke + 49
	12  CoreFoundation                      0x000000010e992454 _CFXRegistrationPost + 496
	13  CoreFoundation                      0x000000010e991d87 _CFXNotificationPost + 806
	14  Foundation                          0x000000010bea09a3 -[NSNotificationCenter postNotificationName:object:userInfo:] + 82
	15  UIKitCore                           0x00000001261372e9 +[UIScene _sceneForFBSScene:create:withSession:connectionOptions:] + 1579
	16  UIKitCore                           0x0000000126db3869 -[UIApplication _connectUISceneFromFBSScene:transitionContext:] + 1299
	17  UIKitCore                           0x0000000126db3d16 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 289
	18  UIKitCore                           0x000000012683339a -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 358
	19  FrontBoardServices                  0x00000001129426f0 -[FBSScene _callOutQueue_agent_didCreateWithTransitionContext:completion:] + 419
	20  FrontBoardServices                  0x000000011296edfb __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke.180 + 102
	21  FrontBoardServices                  0x0000000112950b72 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 209
	22  FrontBoardServices                  0x000000011296e9da __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke + 352
	23  libdispatch.dylib                   0x000000011172ba2c _dispatch_client_callout + 8
	24  libdispatch.dylib                   0x000000011172e923 _dispatch_block_invoke_direct + 295
	25  FrontBoardServices                  0x0000000112995a19 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
	26  FrontBoardServices                  0x000000011299590f -[FBSSerialQueue _targetQueue_performNextIfPossible] + 174
	27  FrontBoardServices                  0x0000000112995a41 -[FBSSerialQueue _performNextFromRunLoopSource] + 19
	28  CoreFoundation                      0x000000010e9c0e15 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	29  CoreFoundation                      0x000000010e9c0d0d __CFRunLoopDoSource0 + 180
	30  CoreFoundation                      0x000000010e9c01e2 __CFRunLoopDoSources0 + 242
	31  CoreFoundation                      0x000000010e9ba941 __CFRunLoopRun + 875
	32  CoreFoundation                      0x000000010e9ba0f3 CFRunLoopRunSpecific + 567
	33  GraphicsServices                    0x00000001173dacd3 GSEventRunModal + 139
	34  UIKitCore                           0x0000000126db1f42 -[UIApplication _run] + 928
	35  UIKitCore                           0x0000000126db6b5e UIApplicationMain + 101
	36  Runner                              0x00000001004d1bff main + 63
	37  dyld                                0x0000000109069ee9 start_sim + 10
	38  ???                                 0x0000000200bdc4fe 0x0 + 8602371326
	39  ???                                 0x0000000000000003 0x0 + 3
)
libc++abi: terminating with uncaught exception of type NSException
dyld4 config: DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot DYLD_LIBRARY_PATH=/Users/enguerrandarminjon/Library/Developer/Xcode/DerivedData/Runner-brwkyruvrfkxfheflvndjdwcajyk/Build/Products/Debug-iphonesimulator:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libMainThreadChecker.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib DYLD_FRAMEWORK_PATH=/Users/enguerrandarminjon/Library/Developer/Xcode/DerivedData/Runner-brwkyruvrfkxfheflvndjdwcajyk/Build/Products/Debug-iphonesimulator
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Unsupported object <CPTabBarTemplate: 0x600002eb1b90> <identifier: 9BF1FB47-1108-4B07-A99D-FB70C58C836C, userInfo: (null), tabTitle: (null), tabImage: (null), showsTabBadge: 0> passed to setRootTemplate:animated:completion:. Allowed classes: (null)'
terminating with uncaught exception of type NSException
CoreSimulator 783.5 - Device: iPhone 6s Plus (7A9868FC-ABE2-4CD0-842F-65ED33B75997) - Runtime: iOS 15.2 (19C51) - DeviceType: iPhone 6s Plus
_LSContextInitReturningError() failed with error Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)" UserInfo={_LSFunction=_LSSchemaConfigureForStore, ExpectedSimulatorHash={length = 32, bytes = 0xf6701f12 bb1a56bb bba5f39f 3f7801a6 ... f9fe6ee0 ef307d24 }, _LSLine=405, WrongSimulatorHash={length = 32, bytes = 0x9da4b2b1 56f7ac19 1a99bc21 b7ec95c2 ... c4004d14 03ef83dc }}
````

**Comment by nimisis** [comment] 2022-03-11 11:44
Same problem here. Using an M1 Pro so added 'arm64' to 'excluded architectures' in the build settings. Emulator is running iOS 15.2

**Comment by EArminjon** [comment] 2022-03-11 11:59
> Same problem here. Using an M1 Pro so added 'arm64' to 'excluded architectures' in the build settings. Emulator is running iOS 15.2

It fix the issue ?

**Comment by nimisis** [comment] 2022-03-11 12:09
Apologies, no the issue remains.

**Comment by EArminjon** [comment] 2022-04-05 21:24
Hi, any news ?

**Comment by EArminjon** [comment] 2022-05-14 13:14
Up ?

**Comment by EArminjon** [comment] 2022-05-22 11:15
up ?

**Comment by oguzhnatly** [comment] 2022-06-05 12:56
Version 1.0.3 has been published in pub.dev. Check it out [here](https://pub.dev/packages/flutter_carplay). 🎉
---
Thank you for @EArminjon's contribution with #14. This issue has been marked as resolved and closed. Please continue the discussion if the issue remains. Please don't forget to join the [Discord Server](https://discord.gg/Xz6WVezFfh), so we can chat over there!

**Closed** 2022-06-05 12:56 UTC
Labels: in testing

**Comment by qiaoming1990321** [comment] 2022-11-15 07:02
i only launch the carplay, in this time , app do not launch, the carplay always gray, there is nothing in the carplay
